var API = window.location.protocol + '//' + window.location.host + "/api/";

function setLang(lang) {
    setLocal('language', lang);
//    $.ajax({
//        url:"index/ajax/lang",
//        type: "POST",
//        dataType: "json",
//        data: {
//            lang: lang
//        },
//        async: true,
//        success: function (res) {
//            // window.location.href = 'index.html';
//        }
//    });
}
function setLang2(lang) {
    setLocal('language', lang);
//    $.ajax({
//        url: API + "set/lang",
//        type: "POST",
//        dataType: "json",
//        data: {
//            lang: lang
//        },
//        async: true,
//        success: function (res) {
//            window.location.href = 'loginTransfer.html';
//        }
//    });
}


function setLocal(name, value) {
    window.localStorage.setItem(name, value)
}

function getLocal(name) {
    return window.localStorage.getItem(name) || '';
}

function changeLg() {
    var lang = '';
    if (getLocal('language') && getLocal('language') == 'en') {
        lang = getLocal('language')
    } else if (getLocal('language') && getLocal('language') == 'hk') {
        lang = getLocal('language')
    } else {
        lang = 'zh';
        setLocal('language', 'zh');
    }
    var urls = JSON.stringify(window.location);
    if (urls.indexOf('black') != -1) {
        $("[data-localize]").localize("text", {
            pathPrefix: "/template/mb/lang",
            language: lang
        });
    } else {
        $("[data-localize]").localize("text", {
        	pathPrefix: "/template/mb/lang",
            language: lang
        });
    }

    setLang(lang)

}
$(function () {
    changeLg();
})
var ts = {
    zh: {
    	ysmmbnwk:"原始密码不能为空",
    	xmmbnwk:"新密码不能为空",
        zjdyh:"尊敬的用户请联系在线客服询问卡号",
        md:"买涨",
        mk:"买跌",
        mcsj:"卖出时间",
        mrfx:"买入方向",
        mrje:"买入金额",
        mrjg:"买入价格",
        mcjg:"卖出价格",
        sjdzje:"实际到账为0",
        txskfs:"请填写收款方式",
        xgdlmm:"修改登录密码",
        xgzjmm:"修改资金密码",
        czsb:"充值失败",
        czcg:"充值成功",
        shz:"审核中",
        txcg:"提现成功",
        txsb:"提现失败",
        enterzzs:"请输入正整数",
        enterzzje:"请输入转账金额",
        zongzichancny:"总资产(CNY)",
        czlxkf:"银行卡充值联系客服",
        daozhanweil:"到账金額为0",
        entertxkh:"请输入正确的提现卡号",
        yishiming:"已实名",
        weishiming:"未实名",
        voltxtNum:"量",
        phoneandemail:"请输入手机号或邮箱",
        fatbalance: '商家余额',
        voltxt: '24H量',
        buy: '买入',
        sell: '卖出',
        revoke: '撤销',
        times: '倍',
        hand: '手',
        phand: '请输入购买手数',
        domore: '做多',
        doless: '做空',
        makemore: "(做多)",
        makeless: "(做空)",
        sure: '确定',
        ceil: '取消',
        ttype: '类型',
        entrustPrice: '委托价',
        oprice: "开仓价",
        tnowprice: "当前价",
        zyprice: "止盈价",
        zsprice: "止损价",
        canbond: "可用保证金",
        optime: "开仓时间",
        pgtime: "平仓时间",
        znum: "折合数量",
        gprice: "隔夜费",
        pcang: "平仓",
        revoke: "撤单",
        fee: "手续费",
        bond: "保证金",
        sureOd: '确认下单',
        ppwd: '请输入交易密码',
        loss: '盈亏',
        setloss: '设置止盈止损',
        expectProfit: '预期盈利',
        expectLoss: '预期亏损',
        allClose: '全部平仓',
        moreClose: '只平多单',
        nullClose: '只平空单',
        sureClose: '确认平仓？',
        thanZearo: '设置的值必须大于0',
        listin: '挂单中',
        tdin: '交易中',
        closein: '平仓中',
        closed: '已平仓',
        revoked: '已撤销',
        revokeOrder: '确认撤销订单么？',
        sureping: '确定平仓？',
        risk: '风险率',
        nomore: '没有更多了',
        nodata: '暂无记录',
        more: '加载更多',
        canuse: '可用',
        frezz: '冻结',
        conversion: '折合',
        tprice: '单价',
        tnum: '数量',
        buyin: '购买',
        sellout: '出售',
        finished: '已完成',
        ceiled: '已取消',
        payed: '已付款',
        nofinish: '未完成',
        waitpay: '待付款',
        buyer: '买家',
        seller: '卖家',
        recever: '收款方',
        time: '时间',
        ttotal: '交易总额',
        withdraw: '撤回',
        see: '查看订单',
        pwaitPay: '请等待买家付款',
        odFinish: '订单已完成',
        odCeil: '订单已取消',
        odPay: '已付款,请仔细查看支付信息',
        buynum: '购买金额',
        sellnum: '卖出数量',
        all: '全部',
        allbuy: '全部买入',
        allsell: '全部卖出',
        tlimit: '限额',
        register_time: '注册时间',
        fiatSub: '所属资产',
        shoper_balance: '商家余额',
        enterShop: '进入店铺',
        abnormal: '异常',
        lowershelf: '下架',
        absure: '确定标记为异常吗？',
        sendsure: '您确定要下架吗？',
        sureceil: '您确定要撤销吗？',
        getcode: '获取验证码',
        plength: '密码的长度在6~30位',
        paccount: '请输入账号！',
        accountlength: '账号的长度在6~16位',
        pinpwd: '请输入密码！',
        ptpwd: '请输入正确的密码！',
        pyan: '请输入验证码！',
        lgsuccess: '登录成功',
        pmobile: '请输入手机号',
        mnot: '输入的邮箱不符合规则',
        tsend: '发送',
        pzpwd: '请填写正确交易密码',
        ptnum: '请输入数量',
        pload: '匹配中,请稍等...',
        pthands: '请选择或者输入手数',
        ptprice: '请输入价格',
        pznum: '手数请输入正整数',
        pnomore: '输入的手数值不能高于',
        pnoless: '输入的手数值不能低于',
        pchange: '该交易对已下架,请重新切换交易对',
        pmethod: '请先选择支付方式',
        ptpwds: '请输入交易密码',
        pmin: '请先输入最小交易量',
        pmax: '请先输入最大交易量',
        nothan: '最大交易量不能小于最小交易量',
        prname: '请输入真实姓名！',
        pid: '请输入身份证件号！',
        pimg: '请上传身份证件照片！',
        pmsg: '请输入信息',
        twonot: '两次密码输入不一致',
        copys: '复制成功',
        pcopy: '请重新复制',
        pdel: '确定删除吗？',
        dels: '删除成功',
        delno: '删除失败',
        pbtotal: '请输入欲购买资产总额',
        pbnum: '请输入欲购买数量',
        pstotal: '请输入欲出售资产总额',
        psnum: '请输入欲出售数量',
        lbuy: '立即购买',
        lsell: '立即出售',
        hnum: '请输入划转数量',
        shua: '是否确认划转？',
        you: "以当前最优价格交易",
        counting: '计算中',
        todoit: '操作',
        pcoin: '请选择货币单位',
        enterEmail: '请输入邮箱号',
        sendCode: "发送验证码",
        seconds: "秒后重新获取",
        load: "加载中...",
        hasPay: '买家已付款，请核实后确认',
        hour: '时',
        minute: '分',
        second: '秒',
        weChatCode: "微信付款码",
        alipayCode: "支付宝付款码",
        weChat: "微信",
        alipay: "支付宝",
        bank: "银行卡",
        business: "商家审核中，请耐心等待",
        apply: "申请",
        remind: "提醒",
        advertise: "您需要先申请成为商家才可发布广告",
        changePassword: "修改密码",
        forgetPassword: "忘记密码",
        resend: "重新发送",
        minimum: "最小提现数量",
        withdrawalAddress: "请输入提币地址",
        withdrawalAmount: "请输入提现数量",
        withdrawals: "输入的提现数量小于最小值",
        balck: "黑色",
        whites: "白色",
        contractAccountBalance: "合约账户余额：",
        description: "请输入描述内容",
        information: "请检查输入信息",
        unbound: "未绑定",
        mobile: '手机',
        bound: "已绑定",
        loginPassword: "登录密码",
        modify: "修改",
        alreadyOpened: "已开启",
        //inviteCode: "邀请码不能为空",
        contractAccount: "合约账户",
        secondContractAccount: "微合约账户",
        Flashexchange: "币币账户",
        c2cAccount: "法币账户",
        hands: "手数",
        multiple: "倍数",
        balance: "余额：",
        oneHanded: "请输入下单手数",
        buyUp: "买涨",
        buyAll: "买跌",
        chooseTime: "请选择时间",
        selectQuantities: "请选择或者输入数量",
        multipleTen: "请输入10的倍数",
        checkoutSuccess: "下单成功",
        klineText1: '分时',
        klineText2: '1分钟',
        klineText3: '5分钟',
        klineText4: '15分钟',
        klineText5: '30分钟',
        klineText6: '1小时',
        klineText7: '1天',
        klineText8: '1周',
        klineText9: '1月',
        lowestNumber: "数量最低为",
        confirmExchange: "确认兑换吗?",
        runningLow: "余额不足",
        purchase: "你输入的数量不符合规则，你的购买额度在",
        reach: "到",
        between: "之间",
        onlyEnter: "你只能输入",
        integersBetween: "之间的整数",
        notReturned: "点击申购保险，视为详细了解保险条约并且同意保险仓自动生效，不能返回。",
        settled: "受保资产亏损至无法下单时，保险理赔",
        profitable: "倍，当资产盈利",
        terminated: "时，保险自动解约。",
        automatically: "当受保资产亏损50%时，必须申请保险理赔，否则无法交易，当盈利100%时，保险自动解约,保险仓每天只允许赔付两次，超过两次，t+1赔付",
        termination: "保险解约后，受保资产方可兑换，解约后视为违约，保险仓自动清零。",
        just: "正",
        back: "反",
        noOpen: "该功能暂未开放",
        match: "兑",
        orderNumber: "订单号",
        entrustmentContract: "委托合约",
        delegateDirection: "委托方向",
        commissionPrice: "委托价格",
        orderQuantity: "下单数量",
        dueTime: "到期结算时间",
        settlementPrice: "结算价格",
        surplus: "盈",
        deficit: "亏",
        ptime: "下单时间",
        countDown: "倒计时",
        emregister1: "邮箱登录",
        phregister1: "手机登录",
        text10:"基于YMT的实时价格",
        czwshjl:"存在未审核提现记录",
        account_limit:"你的账户已冻结请联系客服处理",
        kefu:'客服'
    },
    hk: {
    	ysmmbnwk:"原始密码不能为空",
    	xmmbnwk:"新密码不能为空",
        zjdyh:"尊敬的用戶請聯繫在線客服詢問卡號",
        md:"買涨",
        mk:"賣跌",
        mcsj:"賣出時間",
        mrfx:"買入方向",
        mrje:"買入金額",
        mrjg:"買入價格",
        mcjg:"賣出價格",
        sjdzje:"實際到賬為0",
        txskfs:"請填寫收款方式",
        xgdlmm:"修改登錄密碼",
        xgzjmm:"修改資金密碼",
        czsb:"充值失敗",
        czcg:"充值成功",
        shz:"審核中",
        txcg:"提现成功",
        txsb:"提现失敗",
        enterzzs:"請輸入正整數",
        enterzzje:"請輸入轉賬金額",
        zongzichancny:"總資產(CNY)",
        czlxkf:"銀行卡充值聯繫客服",
         daozhanweil:"到賬金額為0",
        entertxkh:"請輸入正確的提現卡號",
        yishiming:"已實名",
        weishiming:"未實名",
        voltxtNum:"量",
        phoneandemail:"請輸入手機號或郵箱",
        fatbalance: '商家餘額',
        voltxt: '24H量',
        buy: '買入',
        sell: '賣出',
        revoke: '撤銷',
        times: '倍',
        hand: '手',
        phand: '請輸入購買手數',
        domore: '做多',
        doless: '做空',
        makemore: "(做多)",
        makeless: "(做空)",
        sure: '確定',
        ceil: '取消',
        ttype: '類型',
        entrustPrice: '委託價',
        oprice: "開倉價",
        tnowprice: "當前價",
        zyprice: "止盈價",
        zsprice: "止損價",
        canbond: "可用保證金",
        optime: "開倉時間",
        pgtime: "平倉時間",
        znum: "折合數量",
        gprice: "隔夜費",
        pcang: "平倉",
        revoke: "撤單",
        fee: "手續費",
        bond: "保證金",
        sureOd: '確認下單',
        ppwd: '請輸入交易密碼',
        loss: '盈虧',
        setloss: '設定止盈止損',
        expectProfit: '預期盈利',
        expectLoss: '預期虧損',
        allClose: '全部平倉',
        moreClose: '只平多單',
        nullClose: '只平空單',
        sureClose: '確認平倉？',
        thanZearo: '設定的值必須大於0',
        listin: '掛單中',
        tdin: '交易中',
        closein: '平倉中',
        closed: '已平倉',
        revoked: '已撤銷',
        revokeOrder: '確認撤銷訂單麼？',
        sureping: '確定平倉？',
        risk: '風險率',
        nomore: '沒有更多了',
        nodata: '暫無記錄',
        more: '加载更多',
        canuse: '可用',
        frezz: '凍結',
        conversion: '折合',
        tprice: '單價',
        tnum: '數量',
        buyin: '購買',
        sellout: '出售',
        finished: '已完成',
        ceiled: '已取消',
        payed: '已付款',
        nofinish: '未完成',
        waitpay: '待付款',
        buyer: '買家',
        seller: '賣家',
        recever: '收款方',
        time: '時間',
        ttotal: '交易總額',
        withdraw: '撤回',
        see: '查看訂單',
        pwaitPay: '請等待買家付款',
        odFinish: '訂單已完成',
        odCeil: '訂單已取消',
        odPay: '已付款，請仔細查看支付資訊',
        buynum: '購買金额',
        sellnum: '賣出數量',
        all: '全部',
        allbuy: '全部買入',
        allsell: '全部賣出',
        tlimit: '限額',
        register_time: '註冊時間',
        fiatSub: '所屬資產',
        shoper_balance: '商家餘額',
        enterShop: '進入店鋪',
        abnormal: '异常',
        lowershelf: '下架',
        absure: '確定標記為异常嗎？',
        sendsure: '您確定要下架嗎？',
        sureceil: '您確定要撤銷嗎？',
        getcode: '獲取驗證碼',
        plength: '密碼的長度在6~30位',
        accountlength: '账号的长度在6~16位',
        paccount: '請輸入帳號！',
        pinpwd: '請輸入密碼！',
        ptpwd: '請輸入正確的密碼！',
        pyan: '請輸入驗證碼！',
        lgsuccess: '登入成功',
        pmobile: '請輸入手機號',
        mnot: '輸入的郵箱不符合規則',
        tsend: '發送',
        pzpwd: '請填寫正確交易密碼',
        ptnum: '請輸入數量',
        pload: '匹配中，請稍等...',
        pthands: '請選擇或者輸入手數',
        ptprice: '請輸入價格',
        pznum: '手數請輸入正整數',
        pnomore: '輸入的手數值不能高於',
        pnoless: '輸入的手數值不能低於',
        pchange: '該交易對已下架，請重新切換交易對',
        pmethod: '請先選擇支付方式',
        ptpwds: '請輸入交易密碼',
        pmin: '請先輸入最小交易量',
        pmax: '請先輸入最大交易量',
        nothan: '最大交易量不能小於最小交易量',
        prname: '請輸入真實姓名！',
        pid: '請輸入身份證件號！',
        pimg: '請上傳身份證件照片！',
        pmsg: '請輸入資訊',
        twonot: '兩次密碼輸入不一致',
        copys: '複製成功',
        pcopy: '請重新複製',
        pdel: '確定删除嗎？',
        dels: '删除成功',
        delno: '删除失敗',
        pbtotal: '請輸入欲購買資產總額',
        pbnum: '請輸入欲購買數量',
        pstotal: '請輸入欲出售資產總額',
        psnum: '請輸入欲出售數量',
        lbuy: '立即購買',
        lsell: '立即出售',
        hnum: '請輸入劃轉數量',
        shua: '是否確認劃轉？',
        you: "以當前最優價格交易",
        counting: '計算中',
        todoit: '操作',
        pcoin: '請選擇貨幣單位',
        enterEmail: '請輸入郵箱號',
        sendCode: "發送驗證碼",
        seconds: "秒後重新獲取",
        load: "加載中...",
        hasPay: '買家已付款，請核實後確認',
        hour: '時',
        minute: '分',
        second: '秒',
        weChatCode: "微信付款碼",
        alipayCode: "支付寶付款碼",
        weChat: "微信",
        alipay: "支付寶",
        bank: "銀行卡",
        business: "商家稽核中，請耐心等待",
        apply: "申請",
        remind: "提醒",
        advertise: "您需要先申請成為商家才可發佈廣告",
        changePassword: "修改密碼",
        forgetPassword: "忘記密碼",
        resend: "重新發送",
        minimum: "最小提現數量",
        withdrawalAddress: "請輸入提幣地址",
        withdrawalAmount: "請輸入提現數量",
        withdrawals: "輸入的提現數量小於最小值",
        balck: "黑色",
        whites: "白色",
        contractAccountBalance: "合約帳戶餘額：",
        description: "請輸入描述內容",
        information: "請檢查輸入資訊",
        unbound: "未綁定",
        mobile: '手機',
        bound: "已綁定",
        loginPassword: "登入密碼",
        modify: "修改",
        alreadyOpened: "已開啟",
      //  inviteCode: "邀請碼不能為空",
        contractAccount: "合約帳戶",
        secondContractAccount: "秒合約帳戶",
        Flashexchange: "幣幣帳戶",
        c2cAccount: "法幣帳戶",
        hands: "手數",
        multiple: "倍數",
        balance: "餘額：",
        oneHanded: "請輸入下單手數",
        buyUp: "買漲",
        buyAll: "買跌",
        chooseTime: "請選擇時間",
        selectQuantities: "請選擇或者輸入數量",
        multipleTen: "請輸入10的倍數",
        checkoutSuccess: "下單成功",
        klineText1: '分時',
        klineText2: '1分鐘',
        klineText3: '5分鐘',
        klineText4: '15分鐘',
        klineText5: '30分鐘',
        klineText6: '1小時',
        klineText7: '1天',
        klineText8: '1周',
        klineText9: '1月',
        lowestNumber: "數量最低為",
        confirmExchange: "確認兌換嗎?",
        runningLow: "餘額不足",
        purchase: "你輸入的數量不符合規則，你的購買額度在",
        reach: "到",
        between: "之間",
        onlyEnter: "你只能輸入",
        integersBetween: "之間的整數",
        notReturned: "點擊申購保險，視為詳細瞭解保險條約並且同意保險倉自動生效，不能返回。",
        settled: "受保資產虧損至無法下單時，保0險理賠",
        profitable: "倍，當資產盈利",
        terminated: "時，保險自動解約。",
        automatically: "當受保資產虧損50%時，必須申請保險理賠，否則無法交易，當盈利100%時，保險自動解約，保險倉每天只允許賠付兩次，超過兩次，t+1賠付",
        termination: "保險解約後，受保資產方可兌換，解約後視為違約，保險倉自動清零。",
        just: "正",
        back: "反",
        noOpen: "該功能暫未開放",
        match: "兌",
        orderNumber: "訂單號",
        entrustmentContract: "委託合約",
        delegateDirection: "委託方向",
        commissionPrice: "委託價格",
        orderQuantity: "下單數量",
        dueTime: "到期結算時間",
        settlementPrice: "結算價格",
        surplus: "盈",
        deficit: "虧",
        ptime: "下單時間",
        countDown: "倒數計時",
        emregister1: "郵箱登錄",
        phregister1: "手機登入",
        text10:"基於YMT的實时價格",
        czwshjl:"存在未审核提现记录",
        account_limit:"你的账户已冻结请联系客服处理",
        kefu:'客服'


    },
    en: {
    	ysmmbnwk:"Old code cannot be empty",
    	xmmbnwk:"New code cannot be empty",
    	plength: 'The length of the password is 6-30 bits',
    	accountlength: 'The length of the account is 6-16 bits',
        zjdyh:"Dear users, please contact online customer service to ask for the card number",
        md:"Buy rise",
        mk:"Buy fall",
        mcsj:"Sell time",
        mrfx:"Buy direction",
        mrje:"Purchase amount",
        mrjg:"Purchase price",
        mcjg:"Sell price",
        sjdzje:"Actual arrival is 0",
        txskfs:"Please fill in the payment method",
         xgdlmm:"Modify login password",
      xgzjmm:"Change fund password",
        czsb:"Recharge failed",
        czcg:"Top up successfully",
        shz:"under review",
        txcg:"Withdrawal successfully",
        txsb:"Withdraw failed",
        enterzzs:"Please enter a positive integer",
        enterzzje:"Please enter the transfer amount",
        zongzichancny:"Total assets (CNY)",
        czlxkf:"Bank card recharge contact customer service",
          daozhanweil:"The amount received is 0",
        entertxkh:"Please enter the correct withdrawal card number",
        yishiming:"Real name",
        weishiming:"Unnamed",
        voltxtNum:"Vol",
        phoneandemail:"Custom import machine",
        fatbalance: 'Merchant balance',
        voltxt: '24H Vol',
        buy: 'Buy',
        sell: 'Sell',
        revoke: 'Revoke',
        times: "times",
        hand: 'hand',
        phand: "Number of purchases",
        domore: 'Long',
        doless: 'Short',
        makemore: "(Long)",
        makeless: "(Short)",
        sure: 'Sure',
        ceil: 'Cancel',
        ttype: 'type',
        entrustPrice: 'commission price',
        oprice: "Opening price",
        tnowprice: "current price",
        zyprice: "stop earnings price",
        zsprice: "stop-loss price",
        canbond: "available margin",
        pptie: "Opening time",
        optime: 'Open Time',
        pgtime: "Closing time",
        znum: "Converted quantity",
        gprice: "Overnight charges",
        pcang: "Close",
        revoke: "Withdrawal",
        fee: "Service Charge",
        bond: "Bond",
        sureOd: 'confirm order',
        ppwd: 'Fund password',
        setloss: 'Set stop loss stop loss',
        expectProfit: 'expected profit',
        expectLoss: 'expected loss',
        allClose: 'All closing',
        moreClose: 'Only flat more than one',
        nullClose: 'Only empty single',
        sureClose: 'Confirm the position? ',
        thanZearo: 'The value set must be greater than 0',
        listin: 'Pending order',
        tdin: 'in the transaction',
        closein: 'Close the position',
        closed: 'Closed',
        revoked: 'revoked',
        revokeOrder: 'Are you sure to cancel the order? ',
        sureping: 'Determine the closure?',
        risk: 'risk rate',
        nomore: 'No more',
        nodata: 'No record',
        more: 'Load more',
        canuse: 'available',
        frezz: 'freeze',
        conversion: 'Folding',
        tprice: 'Unit Price',
        tnum: 'number',
        buyin: 'Purchase',
        sellout: 'Sell',
        finished: 'Completed',
        ceiled: 'Cancelled',
        payed: 'Paid',
        nofinish: 'incomplete',
        waitpay: 'Pending payment',
        buyer: 'Buyer',
        seller: 'seller',
        recever: 'Payee',
        time: 'time',
        ttotal: 'total',
        withdraw: 'withdraw',
        see: 'View order',
        pwaitPay: 'Please wait for the buyer to pay',
        odFinish: 'The order has been completed',
        odCeil: 'The order has been cancelled',
        odPay: 'Payment has been made. Please check the payment information carefully.',
        buynum: 'Purchase money',
        sellnum: 'Quantity sold',
        all: 'all',
        allbuy: 'Buy all',
        allsell: 'Sell all',
        tlimit: 'Quota',
        register_time: 'Register time',
        fiatSub: 'Assets owned',
        shoper_balance: 'Merchant balance',
        enterShop: 'Enter shop',
        abnormal: 'abnormal',
        lowershelf: 'Lower shelf',
        absure: "Are you sure it's marked as an exception?",
        sendsure: 'Are you sure you want to get off the shelf?',
        sureceil: 'Are you sure you want to revoke it?',
        getcode: 'send',
        paccount: 'Please enter your account! ',
        pinpwd: 'Please enter your password! ',
        ptpwd: 'Please enter the correct password! ',
        pyan: 'Please enter the verification code! ',
        lgsuccess: 'Log on Successfully',
        pmobile: 'Please enter your mobile number',
        mnot: 'Input mailboxes do not conform to the rules',
        tsend: 'Send',
        pzpwd: 'Please fill in the correct transaction password',
        ptnum: 'Please fill in the quantity',
        pload: 'Matching, wait a minute...',
        pthands: 'Please select or enter the number of hands',
        ptprice: 'Please enter the price',
        pznum: 'Please enter a positive integer for the number of hands',
        Pnomore: 'Input hand values should not be higher than',
        pnoless: 'Input hand value must not be lower than',
        pchange: 'The trading pair is off the shelf, please re-switch the trading pair',
        pmethod: 'Please choose the payment method first',
        ptpwds: 'Please enter the transaction password',
        pmin: 'Please enter the minimum transaction volume first.',
        pmax: 'Please enter the maximum volume first',
        nothan: 'Maximum trading volume should not be less than minimum trading volume',
        prname: 'Please enter your real name! ',
        pid: 'Please enter your ID number! ',
        pimg: 'Please upload ID photos! ',
        pPmsg: 'Please enter information',
        twonot: 'inconsistent password input twice',
        copys: 'Copy Successfully',
        pcopy: 'Please reproduce',
        pdel: 'Are you sure you want to delete it? ',
        sels: 'Delete Successfully',
        selno: 'Delete failed',
        pbtotal: 'Please enter the total amount of assets you want to purchase',
        pbnum: 'Please enter the quantity you want to buy',
        pstotal: 'Please enter the total amount of assets you want to sell',
        psnum: 'Please enter the quantity you want to sell',
        lbuy: 'Buy now',
        lsell: 'For immediate sale',
        hnum: 'Please enter the number of transitions',
        shua: 'Do you confirm the transfer?',
        you: "Optimal market price",
        counting: 'In calculation',
        todoit: 'operation',
        pcoin: 'Please choose monetary unit.',
        enterEmail: 'Please enter your mailbox number.',
        sendCode: "Send Verification Code",
        seconds: "Retrieve in seconds",
        load: "loading...",
        hasPay: 'Buyer has paid, please confirm after verification',
        hour: 'hour',
        minute: 'minute',
        second: 'second',
        weChatCode: "Wechat Payment Code",
        alipayCode: "Alipay payment code",
        weChat: "WeChat",
        alipay: "Alipay",
        bank: "Bank",
        business: "Please wait patiently in the process of business audit",
        apply: "Apply",
        remind: "remind",
        advertise: "You need to apply to be a merchant before you can advertise.",
        changePassword: "Change Password",
        forgetPassword: "Forget password",
        resend: "Resend",
        minimum: "Minimum withdrawal amount",
        withdrawalAddress: "Please enter the withdrawal address",
        withdrawalAmount: "Please enter the withdrawal amount",
        withdrawals: "The number of withdrawals entered is less than the minimum",
        balck: "black",
        whites: "white",
        contractAccountBalance: "Contract account balance:",
        description: "Please enter a description",
        information: "Please check the input information",
        unbound: "Unbound",
        mobile: 'mobile',
        bound: "Bound",
        loginPassword: "Login password",
        modify: "modify",
        alreadyOpened: "Already opened",
        //inviteCode: "Invitation code cannot be empty",
        contractAccount: "Contract",
        secondContractAccount: "Second Contract",
        Flashexchange: "Coin exchange",
        c2cAccount: "Fiat account",
        hands: "Number of hands",
        multiple: "Multiple",
        balance: "balance:",
        oneHanded: "Please enter the number of one-handed",
        buyUp: "Buy up",
        buyAll: "Buy or fall",
        chooseTime: "Please choose the time",
        selectQuantities: "Please select or enter quantities",
        multipleTen: "Please enter a multiple of 10",
        checkoutSuccess: "checkout success",
        klineText1: 'Time',
        klineText2: '1min',
        klineText3: '5min',
        klineText4: '15min',
        klineText5: '30min',
        klineText6: '1hour',
        klineText7: '1day',
        klineText8: '1week',
        klineText9: '1mon',
        lowestNumber: "The lowest number is",
        confirmExchange: "Do you confirm the exchange?",
        runningLow: "Sorry, your credit is running low",
        purchase: "The quantity you enter does not conform to the rules. Your purchase quota is",
        reach: "reach",
        between: "between",
        onlyEnter: "You can only enter",
        integersBetween: "Integers between",
        notReturned: "Click to purchase insurance, as a detailed understanding of the insurance treaty and agree that the warehouse will automatically enter into force, can not be returned.",
        settled: "When the insured assets lose money and cannot place an order, the insurance claims shall be settled.",
        profitable: "When assets are profitable",
        terminated: "at that time, the insurance will be automatically terminated.",
        automatically: "When the insured assets lose 50%, they must apply for insurance claims, otherwise they cannot be traded. When the profits are 100%, the insurance will automatically cancel the contract. The warehouse can only pay twice a day, more than twice, t+1.",
        termination: "After the termination of the insurance contract, the insured assets can be converted. After the termination of the contract, the insured assets are deemed to be in breach of contract, and the warehouse is cleared automatically.",
        just: "just",
        back: "back",
        noOpen: "This function is not yet open",
        match: "Match",
        orderNumber: "Order number",
        entrustmentContract: "Entrustment contract",
        delegateDirection: "Delegate direction",
        commissionPrice: "Commission price",
        orderQuantity: "Order quantity",
        dueTime: "Settlement time due",
        settlementPrice: "Settlement price",
        surplus: "Surplus",
        deficit: "Deficit",
        ptime: "Order time",
        countDown: "Count down",
        emregister1: "Mailbox login",
        phregister1: "Mobile login",
        text10:"Real-time Price Based on YMT",
        czwshjl:"There are no audit withdrawal records",
        account_limit:"Your account has been frozen, please contact customer service",
        kefu:'customer service'
    },


};
var lg = getLocal('language') || 'zh';

function getlg(keys) {
    var keys = keys;
    if (getLocal('language') == 'hk') {
        return ts.hk[keys];
    } else if (getLocal('language') == 'en') {
        return ts.en[keys];
    } else {
        return ts.zh[keys];
    }
}

var voltxt = getlg('voltxt');

